# Generated by Django 5.2.6 on 2025-09-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='llave_seguridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
